import java.util.ArrayList;
import java.util.List;

public class DataLoader {
    
    public List<String> getBooks() {
        List<String> books = new ArrayList<>();

        books.add("Genesis");
        books.add("Exodus");
        books.add("Leviticus");
        books.add("Numbers");
        books.add("Deuteronomy");
        books.add("Joshua");
        books.add("Judges");
        books.add("Ruth");
        books.add("1 Samuel");
        books.add("2 Samuel");
        books.add("1 Kings");
        books.add("2 Kings");
        books.add("1 Chronicles");
        books.add("2 Chronicles");
        books.add("Ezra");
        books.add("Nehemiah");
        books.add("Esther");
        books.add("Job");
        books.add("Psalms");
        books.add("Proverbs");
        books.add("Ecclesiastes");
        books.add("Song of Solomon");
        books.add("Isaiah");
        books.add("Jeremiah");
        books.add("Lamentations");
        books.add("Ezekiel");
        books.add("Daniel");
        books.add("Hosea");
        books.add("Joel");
        books.add("Amos");
        books.add("Obadiah");
        books.add("Jonah");
        books.add("Micah");
        books.add("Nahum");
        books.add("Habakkuk");
        books.add("Zephaniah");
        books.add("Haggai");
        books.add("Zechariah");
        books.add("Malachi");
        books.add("Matthew");
        books.add("Mark");
        books.add("Luke");
        books.add("John");
        books.add("Acts");
        books.add("Romans");
        books.add("1 Corinthians");
        books.add("2 Corinthians");
        books.add("Galatians");
        books.add("Ephesians");
        books.add("Philippians");
        books.add("Colossians");
        books.add("1 Thessalonians");
        books.add("2 Thessalonians");
        books.add("1 Timothy");
        books.add("2 Timothy");
        books.add("Titus");
        books.add("Philemon");
        books.add("Hebrews");
        books.add("James");
        books.add("1 Peter");
        books.add("2 Peter");
        books.add("1 John");
        books.add("2 John");
        books.add("3 John");
        books.add("Jude");
        books.add("Revelation");
        books.add("1 Nephi");
        books.add("2 Nephi");
        books.add("Jacob");
        books.add("Enos");
        books.add("Jarom");
        books.add("Omni");
        books.add("Words of Mormon");
        books.add("Mosiah");
        books.add("Alma");
        books.add("Helaman");
        books.add("3 Nephi");
        books.add("4 Nephi");
        books.add("Mormon");
        books.add("Ether");
        books.add("Moroni");
        books.add("Doctrine and Covenants");
        books.add("Moses");
        books.add("Abraham");
        books.add("Joseph Smith-Matthew");
        books.add("Joseph Smith-History");
        books.add("Articles of Faith");

        return books;
    }

    public List<String> getBooksAndChapters() {
        List<String> result = new ArrayList<>();

        result.add("Genesis:50");
        result.add("Exodus:40");
        result.add("Leviticus:27");
        result.add("Numbers:36");
        result.add("Deuteronomy:34");
        result.add("Joshua:24");
        result.add("Judges:21");
        result.add("Ruth:4");
        result.add("1 Samuel:31");
        result.add("2 Samuel:24");
        result.add("1 Kings:22");
        result.add("2 Kings:25");
        result.add("1 Chronicles:29");
        result.add("2 Chronicles:36");
        result.add("Ezra:10");
        result.add("Nehemiah:13");
        result.add("Esther:10");
        result.add("Job:42");
        result.add("Psalms:150");
        result.add("Proverbs:31");
        result.add("Ecclesiastes:12");
        result.add("Song of Solomon:8");
        result.add("Isaiah:66");
        result.add("Jeremiah:52");
        result.add("Lamentations:5");
        result.add("Ezekiel:48");
        result.add("Daniel:12");
        result.add("Hosea:14");
        result.add("Joel:3");
        result.add("Amos:9");
        result.add("Obadiah:1");
        result.add("Jonah:4");
        result.add("Micah:7");
        result.add("Nahum:3");
        result.add("Habakkuk:3");
        result.add("Zephaniah:3");
        result.add("Haggai:2");
        result.add("Zechariah:14");
        result.add("Malachi:4");
        result.add("Matthew:28");
        result.add("Mark:16");
        result.add("Luke:24");
        result.add("John:21");
        result.add("Acts:28");
        result.add("Romans:16");
        result.add("1 Corinthians:16");
        result.add("2 Corinthians:13");
        result.add("Galatians:6");
        result.add("Ephesians:6");
        result.add("Philippians:4");
        result.add("Colossians:4");
        result.add("1 Thessalonians:5");
        result.add("2 Thessalonians:3");
        result.add("1 Timothy:6");
        result.add("2 Timothy:4");
        result.add("Titus:3");
        result.add("Philemon:1");
        result.add("Hebrews:13");
        result.add("James:5");
        result.add("1 Peter:5");
        result.add("2 Peter:3");
        result.add("1 John:5");
        result.add("2 John:1");
        result.add("3 John:1");
        result.add("Jude:1");
        result.add("Revelation:22");
        result.add("1 Nephi:22");
        result.add("2 Nephi:23");
        result.add("Jacob:7");
        result.add("Enos:1");
        result.add("Jarom:1");
        result.add("Omni:1");
        result.add("Words of Mormon:1");
        result.add("Mosiah:29");
        result.add("Alma:63");
        result.add("Helaman:16");
        result.add("3 Nephi:30");
        result.add("4 Nephi:1");
        result.add("Mormon:9");
        result.add("Ether:15");
        result.add("Moroni:10");
        result.add("Doctrine and Covenants:138");
        result.add("Official Declaration:2");
        result.add("Moses:8");
        result.add("Abraham:5");
        result.add("Joseph Smith-Matthew:1");
        result.add("Joseph Smith-History:1");
        result.add("Articles of Faith:1");

        return result;
    }

    public List<String> getTerms() {
        List<String> result = new ArrayList<>();

        result.add("Faith:faith,believe,belief,faithful,faithfulness,trust");
        result.add("Repentance:repentance,repent,forsake,contrite");
        result.add("Forgiveness:forgive,forgiveness,remission");
        result.add("Priesthood:priesthood,priest,authority,ordain,aaronic,melchizedek,ordination,power");
        result.add("Hope:hope,expectation");
        result.add("Love:love,charity,grace,mercy,compassion");
        result.add("Destruction:destruction,destroy,desolate,desolation,perish,waste");
        result.add("Commandments:commandment,commandments,command,commands,law,laws,rule");
        result.add("Seek:seek,sought,inquire,pray,ask,search");
        result.add("Savior:Savior,Jesus,Christ,Son of God,Bread of Life,Jehovah,Advocate,Lamb of God,Son of Man,Redeemer");
        result.add("Revelation:revelation,reveal,prophesy");
        result.add("Baptism:baptism,baptize,baptized,born of water");
        result.add("Covenants:covenant,covenants,promise");
        result.add("Holy Ghost:holy ghost;holy spirit;the spirit;comforter");
        result.add("Pride:pride,proud,hardhearted,stiffnecked");
        result.add("Humility:humility,humble");
        result.add("Happiness:happy,happiness,joy,rejoice");

        return result;
    }
}